services:
  musabotti:
    image: musabotti:latest
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - DISCORD_TOKEN
      - DISCORD_APP_ID
      - PREFIX
      - TIMEOUT_DURATION
      - LAVALINK_NAME
      - LAVALINK_URL
      - LAVALINK_AUTH
    restart: unless-stopped
    depends_on:
      - lavalink
  lavalink:
    image: lavalink:latest
    build:
      context: .
      dockerfile: Dockerfile.lavalink
    ports:
      - 6969:6969
    restart: unless-stopped
    volumes:
      - ./lavacord/application.yml:/opt/Lavalink/application.yml
  # lavalink:
  #   # pin the image version to Lavalink v4
  #   image: ghcr.io/lavalink-devs/lavalink:4
  #   container_name: lavalink
  #   restart: unless-stopped
  #   environment:
  #     # set Java options here
  #     - _JAVA_OPTIONS=-Xmx6G
  #     # set lavalink server port
  #     # - SERVER_PORT=6969
  #     # set password for lavalink
  #     # - LAVALINK_SERVER_PASSWORD=youshallnotpass
  #   volumes:
  #     - ./lavacord/application.yml:/opt/Lavalink/application.yml
  #     # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
  #     - ./lavacord/plugins/:/opt/Lavalink/plugins/
  #   ports:
  #     # you only need this if you want to make your lavalink accessible from outside of containers
  #     - "6969:6969"
